### ISSUE TITLE
Package cannot be installed using composer

### ISSUE THREAD

**Issue by donici** [ngraf/slack-codeception-extension#1]
IIUC, the package needs to be on packagist in order to be able to install it using composer and I think the author is the one that is able to add it there. If that's the case, it would be great if you could do that. Thanks.

**Comment by donici** [comment]
Seems that there is no restriction for who needs to submit it :) I was able to do it.

**Comment by ngraf** [comment]
Thanks for listing it.

Am 05.01.2017 1:49 PM schrieb "Catalin Donici" <notifications@github.com>:
