### ISSUE TITLE
Exception in error handler

### ISSUE THREAD

**Issue by nikolaykolev** [ngraf/slack-codeception-extension#4]
Hi,
I've just tried the plugin, but I can't get it to work. I'm using codeception 2.3 with visualception module.
When I run my acceptance tests with -vvv I can see the following trace:

Exception trace:
 Codeception\Subscriber\ErrorHandler->errorHandler() at /home/fester/PhpstormProjects/razvigor-tests/vendor/ngraf/slack-codeception-extension/src/Extension/SlackExtension.php:258
 Codeception\Extension\SlackExtension->sendFailMessage() at /home/fester/PhpstormProjects/razvigor-tests/vendor/ngraf/slack-codeception-extension/src/Extension/SlackExtension.php:216
 Codeception\Extension\SlackExtension->sendTestResults() at /home/fester/PhpstormProjects/razvigor-tests/vendor/symfony/event-dispatcher/EventDispatcher.php:212
 Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() at /home/fester/PhpstormProjects/razvigor-tests/vendor/symfony/event-dispatcher/EventDispatcher.php:44
 Symfony\Component\EventDispatcher\EventDispatcher->dispatch() at /home/fester/PhpstormProjects/razvigor-tests/vendor/codeception/codeception/src/Codeception/Codecept.php:206
 Codeception\Codecept->printResult() at /home/fester/PhpstormProjects/razvigor-tests/vendor/codeception/codeception/src/Codeception/Command/Run.php:376
 Codeception\Command\Run->execute() at /home/fester/PhpstormProjects/razvigor-tests/vendor/symfony/console/Command/Command.php:252
 Symfony\Component\Console\Command\Command->run() at /home/fester/PhpstormProjects/razvigor-tests/vendor/symfony/console/Application.php:865
 Symfony\Component\Console\Application->doRunCommand() at /home/fester/PhpstormProjects/razvigor-tests/vendor/symfony/console/Application.php:241
 Symfony\Component\Console\Application->doRun() at /home/fester/PhpstormProjects/razvigor-tests/vendor/symfony/console/Application.php:143
 Symfony\Component\Console\Application->run() at /home/fester/PhpstormProjects/razvigor-tests/vendor/codeception/codeception/src/Codeception/Application.php:108
 Codeception\Application->run() at /home/fester/PhpstormProjects/razvigor-tests/vendor/codeception/codeception/package/bin:37
 require() at phar:///usr/local/bin/codecept/autoload.php:12
 require_once() at /usr/local/bin/codecept:5

Let me know if I can provide more information.

**Comment by ngraf** [comment]
Can you provide your configuration of ` Codeception\Extension\SlackExtension:` in your `codeception.yml`?

I guess there is something wrong with 
a) the way you defined your channels
b) my extension

I still run it in production with no problem. Maybe I didn't consider a specific configuration setup.

**Comment by nikolaykolev** [comment]
I've tried to debug and find the issue. The issue was that I didn't have any channels set in the config in the .yml file, although the hook was configured to send messages to me. After configuring it to send the messages to a channel (or me) it worked. 
So I guess the issue is that the basic config doesn't work and a manually set channel/user is required.

**Comment by ngraf** [comment]
Ok, I understand the issue. I will improvement the code so that channel is
not mandatory anymore in the configuration.

Am 26.02.2018 14:43 schrieb "nikolaykolev" <notifications@github.com>:

Closed #4 <https://github.com/ngraf/slack-codeception-extension/issues/4>.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/ngraf/slack-codeception-extension/issues/4#event-1492029008>,
or mute the thread
